// Sample property data for demonstration purposes
window.sampleProperties = [
  {
    id: 1,
    title: "Modern Luxury Villa",
    type: "Villa",
    price: 1250000,
    location: "Beverly Hills, CA",
    beds: 4,
    baths: 3,
    area: 3500,
    status: "active",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Stunning modern villa with panoramic city views",
    features: ["Swimming Pool", "Garage", "Garden", "Security System"]
  },
  {
    id: 2,
    title: "Downtown Penthouse",
    type: "Apartment",
    price: 950000,
    location: "Manhattan, NY",
    beds: 3,
    baths: 2,
    area: 2200,
    status: "active",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Luxury penthouse in the heart of the city",
    features: ["City View", "Modern Kitchen", "Balcony", "Concierge"]
  },
  {
    id: 3,
    title: "Cozy Family Home",
    type: "House",
    price: 675000,
    location: "Suburban Heights, TX",
    beds: 4,
    baths: 2,
    area: 2800,
    status: "sold",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Perfect family home in a quiet neighborhood",
    features: ["Large Yard", "Two-Car Garage", "Updated Kitchen", "Fireplace"]
  },
  {
    id: 4,
    title: "Waterfront Condo",
    type: "Condo",
    price: 780000,
    location: "Miami Beach, FL",
    beds: 2,
    baths: 2,
    area: 1600,
    status: "active",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Beautiful waterfront condo with ocean views",
    features: ["Ocean View", "Beach Access", "Gym", "Pool Deck"]
  },
  {
    id: 5,
    title: "Mountain Retreat",
    type: "House",
    price: 1100000,
    location: "Aspen, CO",
    beds: 5,
    baths: 4,
    area: 4200,
    status: "active",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Luxurious mountain retreat with stunning views",
    features: ["Mountain View", "Ski Access", "Fireplace", "Hot Tub"]
  },
  {
    id: 6,
    title: "City Loft",
    type: "Apartment",
    price: 425000,
    location: "Portland, OR",
    beds: 1,
    baths: 1,
    area: 900,
    status: "pending",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Modern loft in vibrant downtown area",
    features: ["Exposed Brick", "High Ceilings", "Hardwood Floors", "Downtown Location"]
  },
  {
    id: 7,
    title: "Suburban Estate",
    type: "House",
    price: 1850000,
    location: "Westchester, NY",
    beds: 6,
    baths: 5,
    area: 5500,
    status: "active",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Elegant estate home with premium amenities",
    features: ["Tennis Court", "Wine Cellar", "Guest House", "Formal Gardens"]
  },
  {
    id: 8,
    title: "Beachside Villa",
    type: "Villa",
    price: 2200000,
    location: "Malibu, CA",
    beds: 4,
    baths: 3,
    area: 3800,
    status: "sold",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    description: "Stunning beachside villa with private beach access",
    features: ["Beach Access", "Infinity Pool", "Ocean View", "Private Deck"]
  }
];
